[versions]
project = "3.2.4"

[libraries]
lombok = { module = "org.projectlombok:lombok", version = "1.18.30" }
jetbrains_annotations = { module = "org.jetbrains:annotations", version = "24.1.0" }

gson = { module = "com.google.code.gson:gson", version = "2.11.0" }

junit_jupiter = { module = "org.junit.jupiter:junit-jupiter ", version = "5.10.1" }
junit_bom = { module = "org.junit:junit-bom", version = "5.10.1" }

lightdream_logger = { module = "dev.lightdream:logger", version = "4.2.1" }
lightdream_lambda = { module = "dev.lightdream:lambda", version = "5.3.2" }
